### ISSUE TITLE
今後のアプリ機能追加アイデア

### ISSUE THREAD

**Issue by koishi** [xxminamixx/RECRUIT_API#2]
・XMLのパースを簡単に実行できるライブラリで実装する
ポピュラーなライブラリを探してCocoaPodsで導入
目的:外部ライブラリの使用

・フェッチャーの読み込み完了後の動作をDelegateではなくBlocksで実装する
目的:Blocksの使い方の習得

・インジケータを表示する
SVProgressHUDを使ってみましょう
http://qiita.com/sagaraya/items/8a56940402113d683af9
※CocoaPodsで導入
何をどう表示するかは考えてください

・お気に入りの追加、削除はアラートビューよりトーストで表示する
これもSVProgressHUDを使用する。

・一覧にさら読み追加
現状のフェッチャーでは店舗リストを最初の20件？しか表示できない
21件以降もデータが存在するのであれば20件ごとに表示したい

・設定画面にさら読みの設定項目追加
一度に表示する件数を20〜50件など選択可能とする
選択可能なUIパーツは何が良いのかも検討する

・セルの高さを可変にする
店舗一覧でできるかな？

・アプリのアイコン設定
それっぽいアイコンを用意して設定する

・アプリのバージョン情報などを表示する画面を追加
そのまま

・メモリリークの確認
Instrumentsを使ったメモリリークの調査を行う
不具合が見つかれば修正する

・iPad対応、横画面対応
どのデバイス、縦横でも良い感じで表示されるアプリを作る

**Comment by xxminamixx** [comment]
@koishi XMLのパースライブラリやSVProgressHUDについては分からないことが多いので、調査しながら進めていきます。読み込み追加については元のXMLを確認しながら進めます。
